services:
  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: midi
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5342:5432"
    container_name: postgres_db
