services:
  database:
    build:
      context: './database'
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    env_file: .env
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: postgres_db
