version: '3.9'
services:
  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    container_name: postgres_db
